export const selectors = {
    body: "body",
    title: "title",
    header: "#header",
    page: "#page",
    overlay: "#overlay",
    sideMenu: "#side-menu",
    sideMenuTitle: "#side-menu-title",
    pathBox: "#path-box",
    headerMenuBtn: "#header-menu-btn",
    sideNavXBtn: "#side-nav-x-btn",
    lightbulb: "#lightbulb",
    side: "#side",
    sideNav: "#side-nav",
    searchBtn: "#search-btn",
    searchInput: "#search-input",
    wordTip: "#word-tip",
    wordTipBtn: "#word-tip-btn",
    wordTipInner: "#word-tip-inner",
    wordTipUl: "#word-tip-ul",
    footerNav: "#footer-nav",
    sayia: ".sayia",
    sayiaWord: ".sayia-word",
    example: ".example",
    copyBox: ".copy-box",
    copyPmt: ".copy-pmt",
    copyBtn: ".copy-btn",
    innerLink: ".inner-link",
    sideArrow: ".side-arrow",
    GetClear: (selector) => selector.replace("#", "").replace(".", ""),
}
